"""
Node for performing data extraction from the paper text.

This node constructs a combined prompt consisting of a system prompt and a
user prompt and passes it to the ``extraction_extractor`` from
:mod:`knowmat.extractors`. The system prompt is generated by
:func:`knowmat.prompt_generator.generate_system_prompt` and can be modified by
the sub-field detection and evaluation agents via ``state['updated_prompt']``.

Primary path uses TrustCall tool extraction. A conservative raw-JSON fallback
is kept for providers with unstable tool-call compatibility.
"""

import json
import logging
import re
from typing import Any, Dict

from knowmat.extractors import CompositionList, extraction_extractor, get_llm
from knowmat.prompt_generator import generate_system_prompt, generate_user_prompt
from knowmat.states import KnowMatState
from knowmat.app_config import settings

logger = logging.getLogger(__name__)


def _flatten_message_content(content: Any) -> str:
    """Best-effort conversion from chat content blocks into plain text."""
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        parts = []
        for block in content:
            if isinstance(block, str):
                parts.append(block)
            elif isinstance(block, dict):
                parts.append(str(block.get("text") or block.get("content") or ""))
            else:
                parts.append(str(block))
        return "\n".join(part for part in parts if part).strip()
    return str(content or "")


def _extract_json_object_text(text: str) -> str:
    """Extract the first valid JSON object from free-form model output."""
    payload = str(text or "").strip()
    if payload.startswith("```"):
        payload = re.sub(r"^```(?:json)?\s*", "", payload)
        payload = re.sub(r"\s*```$", "", payload)
    try:
        json.loads(payload)
        return payload
    except Exception:
        pass

    decoder = json.JSONDecoder()
    for match in re.finditer(r"\{", payload):
        try:
            obj, _ = decoder.raw_decode(payload[match.start():])
        except Exception:
            continue
        if isinstance(obj, dict):
            return json.dumps(obj, ensure_ascii=False)
    raise ValueError("Could not locate a valid JSON object in fallback response.")


def _invoke_plain_json_fallback(full_prompt: str) -> Dict[str, Any]:
    """Fallback path for providers that fail structured tool calling."""
    llm = get_llm(agent_type="extraction")
    fallback_prompt = (
        full_prompt
        + "\n\nIMPORTANT: Do not call any tool."
        + "\nReturn raw JSON only."
        + "\nReturn exactly one JSON object with top-level key `compositions`."
    )
    response = llm.invoke(fallback_prompt)
    content = _flatten_message_content(getattr(response, "content", response))
    payload = _extract_json_object_text(content)
    model = CompositionList.model_validate_json(payload)
    return json.loads(model.model_dump_json())


def extract_data(state: KnowMatState) -> Dict[str, Any]:
    """Perform the main LLM extraction and return the structured data."""
    paper_text = state.get("paper_text", "")
    sub_field = state.get("sub_field")
    prompt_updates = state.get("updated_prompt", "").strip()

    # Stage 2: inject multimodal figure descriptions into paper_text before extraction
    if settings.figure_description_enabled:
        ocr_items = state.get("ocr_items") or []
        if ocr_items:
            from knowmat.pdf.figure_describer import inject_figure_descriptions
            logger.info("Injecting figure descriptions into paper_text...")
            try:
                paper_text = inject_figure_descriptions(paper_text, ocr_items)
                logger.info("✓ Figure descriptions injected.")
            except Exception as exc:
                logger.warning("Figure description injection failed: %s", exc, exc_info=True)

    system_prompt = generate_system_prompt(sub_field=sub_field)
    if prompt_updates:
        system_prompt = system_prompt.strip() + "\n\n" + prompt_updates

    user_prompt = generate_user_prompt(paper_text)
    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_prompt},
        {"role": "user", "content": "Provide your response using the tool."},
    ]
    full_prompt = system_prompt + "\n\n" + user_prompt + "\n\n" + (
        "Provide your response using the tool."
    )

    structured_error: Exception | None = None
    try:
        result = extraction_extractor.invoke({"messages": messages})
    except Exception as exc:
        structured_error = exc
        logger.warning(
            "Structured extraction with role-separated messages failed; "
            "falling back to legacy prompt. Error: %s",
            exc,
        )
        try:
            result = extraction_extractor.invoke(full_prompt)
        except Exception as exc2:
            logger.warning("Legacy structured extraction also failed: %s", exc2)
            result = None

    responses = (result or {}).get("responses") or []
    if not responses:
        try:
            fallback_result = extraction_extractor.invoke(full_prompt)
        except Exception as exc:
            if structured_error is None:
                structured_error = exc
            else:
                logger.warning("Structured fallback returned no responses: %s", exc)
            fallback_result = None
        responses = (fallback_result or {}).get("responses") or []

    if not responses:
        logger.warning(
            "Tool-based extraction returned no structured responses; "
            "attempting raw-JSON fallback."
        )
        try:
            extracted_dict = _invoke_plain_json_fallback(full_prompt)
            return {"latest_extracted_data": extracted_dict}
        except Exception as fallback_exc:
            if structured_error is not None:
                raise RuntimeError(
                    "Extraction failed in both structured and raw-JSON modes: "
                    f"{structured_error}; fallback={fallback_exc}"
                ) from fallback_exc
            raise

    response = responses[0]
    if isinstance(response, CompositionList):
        extracted_dict = json.loads(response.model_dump_json())
    else:
        extracted_dict = response
    return {"latest_extracted_data": extracted_dict}
